### ISSUE TITLE
Bugs with other mods

### ISSUE THREAD

**Issue by RedTeaBaby** [Ezzenix/SmoothGui#10]
When applied together with EMI, there may be an issue where the icon and actual position cannot correspond. Version 1.21.1
![Uploading QQ20241228-015416.png…]()

**Comment by RedTeaBaby** [comment]
![Uploading QQ20241228-015416.png…]()

**Comment by RedTeaBaby** [comment]
![QQ20241228-015416](https://github.com/user-attachments/assets/4964b566-6efd-4aed-a845-5d2494219257)

**Comment by mpustovoi** [comment]
+1 Having issues with EMI mod.
Why complemed?
